apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${cluster_issuer_name} # letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${email_address}
    privateKeySecretRef:
      name: ${cluster_issuer_name} # letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: azure/application-gateway 
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux
